---
- hosts: ispconfig_remote
  become: false
  
  tasks:
    - name: include general variables
      include_vars: server-vars.yml
      
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - python3-pymysql
      
    - name: update passwords remotely
      script: "get_remote_email_passwords_mysql.py {{ ispconfig_mysql_root_password }}"
      args:
        executable: python3
      register: result
    
    - name: Check for {{ email_password_file }}
      local_action: stat path={{ email_password_file }}
      register: file_exists
    
    - debug: msg="{{file_exists}}"
    
    - local_action: copy content={{ result.stdout }} dest={{ email_password_file }}
      when: "file_exists.stat.exists != True"
    
