---
- hosts: ispconfig
  become: false

  tasks:
    - name: include general variables
      include_vars: server-vars.yml
      
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      become: yes
      vars:
        packages:
          - python3-pymysql

    - name: Check for {{ email_password_file }}
      local_action: "stat path={{ email_password_file }}"
      register: file_exists
      failed_when: "file_exists.stat.exists != True"
          
          
    - name: Copy password file to remote
      ansible.builtin.copy:
        src: "{{ email_password_file }}"
        dest: "{{ email_password_file }}"
    
    - name: update passwords remotely
      script: "set_email_passwords_mysql.py {{ ispconfig_mysql_root_password }} {{ email_password_file }}"
      args:
        executable: python3
      register: result
    
    - name: Remove/delete remote password file
      ansible.builtin.file:
        path: "{{ email_password_file }}"
        state: absent
